# Site settings
title: Ziyuan Zhang
description: Ziyuan Zhang's homepage
# baseurl: "https://github.com/bobothebest" # the subpath of your site, e.g. /blog
# url: "https://bobothebest.blog" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ziyuan Zhang(张梓源)
user_description: I am now a first-year graduate student majoring in Mathematical Finance and Fintech in the School of Statistics and Management of Shanghai University of Finance and Economics (SUFE). My tutor is Qiu Yixuan. In fall 2023, I will attend Boston University to study the Mathematical Finance & Financial Technology (MSMFT) program.
user_title: First year graduate student, School of Statistics and Management, SUFE
email: xiguifei@bu.edu
# twitter_username: lorem_ipsum
#instagram_username: mauriciourraco7
#facebook_username: mauricio.urraco
#linkedin_username: Ziyuan Zhang
github_username:  bobothebest
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

