# Site settings
title: Ziyuan Zhang
description: Ziyuan Zhang's homepage
# baseurl: "https://github.com/bobothebest" # the subpath of your site, e.g. /blog
# url: "https://bobothebest.blog" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ziyuan Zhang(张梓源)
user_description: I am currently a second-year graduate student pursuing a joint degree program between Shanghai University of Finance and Economics (SUFE) and Boston University. I am studying in the MSMFT (Master of Science in Mathematical Finance and Technology) program at Boston University's Questrom School of Business, and expect to graduate in 2025.
user_title: Second-year graduate student, SUFE-BU joint degree program
email: xiguifei@bu.edu
# twitter_username: lorem_ipsum
#instagram_username: mauriciourraco7
#facebook_username: mauricio.urraco
linkedin_username: Ziyuan Zhang
github_username:  bobothebest
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

